### PR TITLE
[Fixes #26] Fix drop shadows

### LINKED ISSUE #26: Drop shadows are broken
- [x] If `dropShadowDistance` is too big, then drop shadows get cut off.
- [x] `dropShadowBlur` seems to do nothing at all.
- [x] If one text style has a drop shadow that should be behind previous text, it is instead drawn on top of the previous text.
- [x] `dropShadowAngle` is measured from the wrong base angle.

### PR DESCRIPTION
**Pull request by bluepichu**
More or less what it says on the tin:

- Drop shadows are no longer cut off.
- Drop shadows now blur properly.
- Drop shadows are no longer drawn on top of other text.
- Drop shadows now measure their angles properly.

Interestingly, this makes our version of drop shadows better than `PIXI.Text`'s, which fails both of the first two points.  Perhaps I'll file a PR on Pixi itself as well at some point...

### CODE REVIEW

File: pixi-multistyle-text.ts [hunk 1]
```diff
@@ -148,6 +155,19 @@ export default class MultiStyleText extends PIXI.Text {
 		};
 	}
 
+	private getDropShadowPadding(): number {
+		let maxDistance = 0;
+		let maxBlur = 0;
+
+		for (let styleKey of Object.keys(this.textStyles)) {
```
Comment (tleunen) [inline pixi-multistyle-text.ts]: I'm not a huge fan of `for of`. Instead, I'd prefer `Object.keys(this.textStyles).forEach(...)`
Unless there's a huge gain of performance by using for of?

File: pixi-multistyle-text.ts [hunk 2]
```diff
@@ -224,94 +239,114 @@ export default class MultiStyleText extends PIXI.Text {
...
 
-				if (textStyle.valign === "bottom") {
-					linePositionY += lineHeights[i] - line[j].height -
-						(maxStrokeThickness - textStyle.strokeThickness) / 2;
-				} else if (textStyle.valign === "middle") {
-					linePositionY += (lineHeights[i] - line[j].height) / 2 -
-						(maxStrokeThickness - textStyle.strokeThickness) / 2;
-				}
+		// First pass: draw the shadows only
+		for (let { style, text, x, y } of drawingData) {
```
Comment (tleunen) [inline pixi-multistyle-text.ts]: Same here. `drawingData.forEach(({ style, text, x, y }) => { ... });` would be best

File: pixi-multistyle-text.ts [hunk 3]
```diff
@@ -224,94 +239,114 @@ export default class MultiStyleText extends PIXI.Text {
...
+			this.context.font = PIXI.Text.getFontStyle(style);
```
Comment (tleunen) [inline pixi-multistyle-text.ts]: Should this line be after the `continue` condition?

File: pixi-multistyle-text.ts (hunk 1 above)
Comment (bluepichu) [inline pixi-multistyle-text.ts]: As it turns out, `of` is slower, actually.  Fixed.

File: pixi-multistyle-text.ts (hunk 2 above)
Comment (bluepichu) [inline pixi-multistyle-text.ts]: Fixed, as well as for the next one.

File: pixi-multistyle-text.ts (hunk 3 above)
Comment (bluepichu) [inline pixi-multistyle-text.ts]: It doesn't matter, but there's no reason to do it in every case.  Fixed.
