### PR TITLE
Fix/demo

### LINKED ISSUE #81: demo no longer works
npm run demo  --> 'open' is not recognized as an internal or external command,
npm run build and open index.html in your browser -> multistyletext is undefined

### PR DESCRIPTION
**Pull request by mimshwright**
Fixes #81 
Added a check for undefined `setRealSize()` which seems to fix it for me. Also added `opener` package for cross-platform open.

### CODE REVIEW

File: src/pixi-multistyle-text.ts [hunk 1]
```diff
@@ -879,7 +879,9 @@ export default class MultiStyleText extends PIXI.Text {
 
 		let dropShadowPadding = this.getDropShadowPadding();
 
-    texture.baseTexture.setRealSize(this.canvas.width, this.canvas.height, this.resolution);
+    if (texture.baseTexture.setRealSize) {
```
Comment (tleunen) [inline src/pixi-multistyle-text.ts]: This exists in Pixi v5, which is the only version we're now supporting going forward.
If you need this, it's because you're still using Pixi v4, therefore you should use pixi-multistyle-text v0.8.0

Comment (mimshwright) [reply src/pixi-multistyle-text.ts]: If this is the case then we should just message the user if the version is old. I added another commit. 

Also, the reason this is happening in the demo is because the HTML for the demo page is loading the old version of Pixi.
`<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.5.6/pixi.js"></script>`

File: demo/index.html [hunk 2]
```diff
@@ -6,7 +6,7 @@
 	<link rel="stylesheet" href="style.css" />
 	<link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
 
-	<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.5.6/pixi.js"></script>
+	<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.2.0/pixi.js"></script>
```
Comment (mimshwright) [inline demo/index.html]: @tleunen After changing the version here the canvas in the demo page no longer extends to the bottom of the screen. I'm not sure exactly why that may be the case or if it's intended, but maybe you can take a look.

Comment (tleunen) [reply demo/index.html]: This is because the api changed.
`PIXI.autoDetectRenderer` takes an option object now.
```
let renderer = PIXI.autoDetectRenderer({
      width: 600,
      height: 3425
    });
```

Comment (tleunen) [reply demo/index.html]: I've fixed it on master already. So you can rebase and only keep the `open` fix here now ;)
Thanks a lot for your contributions tho!

**Comment by mimshwright** [comment]
updated.

**Comment by tleunen** [comment]
Thank you @mimshwright !
