### PR TITLE
[Fixes #12] Add Browserify to build

### LINKED ISSUE #12: Export module
Hi,

I encountered some problems during installation of your module.

We used pixi as a dependency in our project, so not like in your demo in a simple html file.

So we have to export your class for make a require in the other files were we need to use MultiStyleText.

Is this normal ? Did i do something wrong ?

Thanks :)

### PR DESCRIPTION
**Pull request by bluepichu**
Turns out the fix I had before was a full fix: the `.d.ts` issues I was having were due to setup errors on my end.

**EDIT: No longer has any breaking changes.**

---

_The following no longer applies.  I'm keeping it here so that the discussion below makes sense._

**Breaking change**: `MultiStyleText` is now wrapped in a module, which means that even when including this package via a `<script>` tag, you need to "unwrap" it to use it:

```js
let textSample = new MultiStyleText.MultiStyleText("It's sad, but required.");
```

### CODE REVIEW

File: pixi-multistyle-text.ts [hunk 1]
```diff
@@ -2,11 +2,11 @@
 
 "use strict";
 
-interface ExtendedTextStyle extends PIXI.TextStyleOptions {
+export interface ExtendedTextStyle extends PIXI.TextStyleOptions {
 	valign?: "top" | "middle" | "bottom";
 }
 
-interface TextStyleSet {
+export interface TextStyleSet {
```
Comment (tleunen) [inline pixi-multistyle-text.ts]: Is it necessary/useful to export the interfaces?

File: package.json [hunk 2]
```diff
@@ -32,12 +32,14 @@
...
   "devDependencies": {
+    "browserify": "^13.1.1",
+    "tsify": "^2.0.7",
     "@types/pixi.js": "^4.3.1",
     "typescript": "^2.1.4"
   },
   "scripts": {
     "demo": "npm run build && open demo/index.html",
-    "build": "tsc",
+    "build": "tsc; browserify pixi-multistyle-text.ts -p tsify -s MultiStyleText -o dist/pixi-multistyle-text.js -d",
```
Comment (tleunen) [inline package.json]: I thought `tsc` was already compiling down to basic JS. Could you explain why browserify is required here?

Also, I'd like to find a way to remove the new wrapped module to remove the duplication`MultiStyleText.MultiStyleText` when the file is injected in a script tag instead of using a commonjs require/import for example.

File: pixi-multistyle-text.ts (hunk 1 above)
Comment (bluepichu) [inline pixi-multistyle-text.ts]: Yes, it's required - you can't export the `MultiStyleText` class if it has properties or methods that use types that wouldn't be accessible externally.

File: package.json (hunk 2 above)
Comment (bluepichu) [inline package.json]: The point of Browserify here is to export the module for CommonJS and AMD if either of those are being used, and otherwise defaulting to a global export.  This is similar to how Pixi itself functions (and they also use Browserify to build).  I was originally hoping we could get away with using TS's `umd` module mode, which handles both CommonJS and AMD properly, but it doesn't default to exposing the module globally if neither is found.

I'd also like to remove the "double wrapping" problem if possible, but I couldn't find a way to do so.  (In particular, I would've expected that `export default class MultiStyleText` would do the trick, but that instead exports the class to `MultiStyleText.default`.)

I'll keep looking into it.

Comment (bluepichu) [inline package.json]: I found a solution.  I don't love it (it's kind of a hack), but it works.  See TypeStrong/tsify#105.
